Feature/aboutUsSection
FooCamp/fundacion-manao pull request #12
Opened 2022-11-02 04:04 UTC by jcmonsa

aboutUsSection component created including the following files:

TEMPLATES:
1. aboutUsSection.hbs
2. personCard.hb

SCSS-COMPONENTS:
1. _aboutussection.scss

STATIC-IMAGES:
1. image 8.png
2. image 8.png
3. image 15.png
4. quotation_close.svg
5. quotation_open.svg

![aboutUsSection](https://user-images.githubusercontent.com/53483203/199393001-f160fee8-1e5b-423a-93e4-fb5701efd689.PNG)

2022-11-02 13:17 UTC, jrmahechad requested changes
Hi @jcmonsa Great job!
I added a couple of comments to improve the structure and naming a little bit.

2022-11-02 13:17 UTC, jrmahechad commented on templates/aboutUsSection.hbs
> +<div class="container1">
I would suggest having a <section> wrapping all the content of this component.
Also you can improve naming on the classes. For example 

```
<section class="aboutus">
    <div class="aboutus__heading">
       <h2 class="about_us__eyebrow">
... and so on
```

2022-11-02 13:17 UTC, jrmahechad commented on templates/aboutUsSection.hbs
> +  <div class="quotation-marks1">
I would suggest a class name like quotation-marks__open and quotation-marks__close to improve naming!

2022-11-02 17:28 UTC, JFozzie commented on templates/aboutUsSection.hbs
> +    <svg width="60" height="47" viewBox="0 0 60 47" fill="none" xmlns="http://www.w3.org/2000/svg">
Load the svg file from an img tag

2022-11-02 17:58 UTC, jrmahechad approved these changes

2022-11-02 20:27 UTC, jcmonsa commented on templates/aboutUsSection.hbs
> +    <svg width="60" height="47" viewBox="0 0 60 47" fill="none" xmlns="http://www.w3.org/2000/svg">
Hello Jordy, done :)! ty

2022-11-02 22:44 UTC, annamarriap commented
Hi @jcmonsa.
In the person_card element you are missing the bottom  shadow, is hard to read without it.

![Screen Shot 2022-11-02 at 5 41 03 PM](https://user-images.githubusercontent.com/10470288/199616072-33dce0aa-fc76-4a76-ac2a-79320151ace9.png)

```
background: linear-gradient(180deg, rgba(0, 16, 48, 0) 0%, #001030 96.87%);
```

2022-11-02 23:14 UTC, jsebax commented
@jcmonsa Please add the Hover functionality. Show the corresponding quote for each Card

2022-11-05 22:18 UTC, jsebax commented on src/scss/components/_aboutussection.scss
> +  color: #fff;
Please use the variables defined for the colors. In the file `_variables.scss`

2022-11-05 22:18 UTC, jsebax commented on src/scss/components/_aboutussection.scss
> +  color: #fff;
Same here

2022-11-05 22:18 UTC, jsebax commented on src/scss/components/_aboutussection.scss
> +  color: #576684;
Same here

2022-11-07 19:25 UTC, jsebax approved these changes

2022-11-07 19:26 UTC, merged