Fixed statistics styles in mobile
FooCamp/fundacion-manao pull request #22
Opened 2022-11-07 16:30 UTC by LiniSabri

2022-11-08 13:21 UTC, jrmahechad requested changes
Hi @LiniSabri great work! can you double check the page and add a margin botton so the component doesnt overlap with the cards bellow? 

![image](https://user-images.githubusercontent.com/5782744/200575399-4dfd736b-70ef-4b07-986b-96c0833bf8e3.png)

![image](https://user-images.githubusercontent.com/5782744/200575528-23de49a2-4aeb-48ea-b73f-7ab5b7869786.png)

2022-11-09 18:12 UTC, jsebax commented
<img width="866" alt="image" src="https://user-images.githubusercontent.com/11170707/200907783-56ac4acb-5edb-4277-8167-1d290e00f731.png">


@jrmahechad If you check the designs, the carousel should overlap the previous component. So, it is the expected behavior. The right position should be handled by the carousel component, not this one.

2022-11-09 18:17 UTC, jsebax approved these changes

2022-11-10 13:19 UTC, jrmahechad approved these changes

2022-11-10 13:19 UTC, merged