Feature/services tabs
FooCamp/fundacion-manao pull request #42
Opened 2022-11-18 07:47 UTC by JFozzie

Services Tabs component

Created files:

- _servicesTab.js
- _servicesTab.scss
- serviceComponent.hbs
- servicesTab.hbs

Trello ticket
https://trello.com/c/HNznSYPh

Slug:
http://localhost:8080/servicestabs.html

https://user-images.githubusercontent.com/111401432/202648293-2c07b2d4-f3f2-4721-a3e3-e86f34ae7578.mp4

2022-11-22 21:42 UTC, jrmahechad requested changes
@JFozzie great job!. Pnly a small comment to improve accessibility

2022-11-22 21:42 UTC, jrmahechad commented on templates/servicesTab.hbs
> +  <div class="tab__name">
@JFozzie Can you update this using a button tag? This will improve accessibility.

2022-11-22 23:46 UTC, jrmahechad commented on templates/serviceComponent.hbs
> +      {{#each serviceTabs}}
@jsebax Do you know if we can call a diferent hbs file here?  Looks like we need to split this in two components one serviceTabsHeader and other serviceTabsContent.  

Jordy is duplicating the content and then removing it from JS

2022-11-23 20:33 UTC, jsebax commented on templates/serviceComponent.hbs
> +      {{#each serviceTabs}}
Ok. It sounds good. Let's split the content into two components

2022-11-23 20:40 UTC, jsebax commented
@JFozzie You are missing the Component title that has the shape. You can implement the different shape variations since they are now included in the Figma design. Please review
<img width="899" alt="image" src="https://user-images.githubusercontent.com/11170707/203642012-dae410d0-5fe7-41cc-b099-7548c5e84b11.png">

2022-11-25 20:35 UTC, jrmahechad approved these changes

2022-11-25 20:40 UTC, jsebax approved these changes
Good job 👍

2022-11-25 20:40 UTC, merged