Feature/attribute services
FooCamp/fundacion-manao pull request #44
Opened 2022-11-22 14:35 UTC by LindaNieves23

AttributeServices

Component for Mobile and desktop created including the file:

HBS:
 serviceAttribute.hbs
 serviceAttributesContainer.hbs

CSS:
 _serviceAttributesContainer.scss

Test Page:
http://localhost:8080/AttributesPage.html

Link Trello:
https://trello.com/c/ajU7IArq

2022-11-22 21:49 UTC, jrmahechad approved these changes

2022-11-22 21:50 UTC, jrmahechad requested changes
@LindaNieves23 great job. I added a small comment

2022-11-22 21:50 UTC, jrmahechad commented on templates/serviceAttribute.hbs
> +<div class='container__attribute-section--title container__attribute-section--box'>{{title}}
This should be a p tag

2022-11-22 21:50 UTC, jrmahechad commented on templates/serviceAttribute.hbs
> +<div class='container__attribute-section--value container__attribute-section--box'>{{values}}
This should be a p tag

2022-11-23 20:09 UTC, jsebax commented on templates/serviceAttributesContainer.hbs
> +  <a class='link-date'>{{{module bookNowButton}}}</a>
If you put the `module bookNowButton` inside an `<a>` tag, you'll have two anchor links. Remove the `<a>` tag around and just leave the `{{{module bookNowButton}}}` code, and use the `.link` class that the `bookNowButton` has to specify your button styles.

2022-11-23 23:06 UTC, jrmahechad approved these changes

2022-11-23 23:44 UTC, jrmahechad approved these changes

2022-11-23 23:44 UTC, merged