Created Aliados section
FooCamp/fundacion-manao pull request #8
Opened 2022-10-27 16:51 UTC by LindaNieves23

Aliados component created including the file:

HTML:
 logosSection.hbs

CSS:
 _logosSection.scss

Functionalities:
use shapes as background
Integration with CMS content(eyebrow and logos list).

Test Page:
http://localhost:8080/linda-page.html

Link Trello:
https://trello.com/c/r7J5GQ16

preview
https://user-images.githubusercontent.com/44320336/198351215-6efa90b0-6de8-439e-a55a-8fc330d3801b.mp4

2022-10-27 17:06 UTC, jrmahechad requested changes
Hi @LindaNieves23 Great work!!! 

I added some suggestions to the PR

2022-10-27 17:06 UTC, jrmahechad commented on templates/logosSection.hbs
> +  <img class='aliados-wrapper__shape-a' src="/image/Shape-A.svg" alt="shape-A">
In this case I think you can use alt="" this images are decorative and don't need read when using a screen reader.<

2022-10-27 17:06 UTC, jrmahechad commented on templates/logosSection.hbs
> +  <img class='aliados-wrapper__shape-o' src="/image/Shape-O.svg" alt="shape-O">
In this case I think you can use alt="" this images are decorative and don't need read when using a screen reader.<

2022-10-27 17:06 UTC, jrmahechad commented on src/scss/components/_logosSection.scss
> +.aliados-wrapper {
I would suggest using english names in general. I think "sponsors" is a good word instead of "aliados"

2022-10-27 17:06 UTC, jrmahechad commented on src/scss/components/_logosSection.scss
> +.aliados-section {
Same comment about the name here

2022-10-27 17:06 UTC, jrmahechad commented on templates/logosSection.hbs
> +<section class="aliados-wrapper">
Same recommendation about the name in english. Also is a good practice to be consistent with the names across files. So, I would suggest to rename the file to sponsorsSection.hbs

2022-10-27 17:06 UTC, jrmahechad commented on src/scss/components/_logosSection.scss
> +.aliados-wrapper {
Also I would recommend to change the filename to _sponsorsSection.scss for consistency

2022-10-27 21:26 UTC, Alex-Cortes-87 commented on src/scss/components/_logosSection.scss
> +    width: 491.6px;
Please use rem values.

2022-10-31 14:04 UTC, jrmahechad requested changes

2022-10-31 14:04 UTC, jrmahechad commented on src/scss/main.scss
> +@import 'components/logosSection';
Plase update from develop branch and fix conflicts

2022-10-31 14:04 UTC, jrmahechad commented on templates/logosSection.hbs
> +  <img class='sponsors-wrapper__shape-a' src="/image/Shape-A.svg">
Please add the alt atribute empty like this `alt=""` for this and the images below.

2022-11-02 22:40 UTC, jsebax approved these changes

2022-11-02 23:03 UTC, jrmahechad approved these changes

2022-11-02 23:04 UTC, merged